### ISSUE TITLE
Optimize the getUserCourses API

### ISSUE THREAD

**Issue by mohitisimmortal** [mohitisimmortal/fusion-courses#1]
### Optimization: Implementing Pagination
To avoid fetching all courses at once, you can implement pagination on the backend and frontend.

### 1. Backend Pagination:
Modify the backend to return only a subset of courses based on page number and limit

File location- backend/controllers/userController.js
Controller to update-
exports.getUserCourses = async (req, res) => {
    ................
};

### 2. Frontend: Adjust to Handle Pagination:
Modify the fetchCourses function to request only a subset of courses based on the current page
Modify the "Show more..." button to load more courses:

File location- frontend/src/components/section3/Section3.jsx

**Comment by Dungho123d** [comment]
Hi @mohitisimmortal , I'd like to help with this issue. Could you please assign it to me?

**Comment by mohitisimmortal** [comment]
ok, do it
btw, this issue will be solve in around 1-2 hrs, if you taking more time then tell me i'll help you!

**Comment by Dungho123d** [comment]
Hi! I solved this issue and pushed it in my branch. Please check it and give me feedback. Thank you!

**Comment by mohitisimmortal** [comment]
make a PR, will check!

**Comment by Dungho123d** [comment]
I haved make a PR in master branch.
Please check it and give me a feedback.

**Comment by mohitisimmortal** [comment]
I think you didn't test it, have a bug that didn't fetch last page of courses, but no worries i implement new code, 
Thanks so much for giving your time.
